---
_extends: gh-plumbing:.github/commons-settings.yml

repository:
  name: ansible_playbook-baseline-k3s
  description: Bootstrapping k3s.
  homepage: https://nolte.github.io/ansible_playbook-baseline-k3s
  topics: ansible, ansible-playbook, bootstrapping, k3s

branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: true
      restrictions: null
  - name: develop
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - "Ansible Lint / molecule (push)"
      restrictions: null
