---
- hosts: k3sPrimary
  become_method: sudo
  become: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:
    - command: kubectl get nodes
    - debug:
        msg: "{{ item }}"
      with_items:
        - "{{ groups['k3s'] }}"
