---
- hosts: k3sPrimary
  become_method: sudo
  become: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:
    - command: kubectl get nodes
    - debug:
        msg: "{{ hostvars[item].k3s_node_roles }}"
      with_items:
        - "{{ groups['k3s'] }}"
    - debug:
        msg: "{{ hostvars[item].k3s_node_roles }}"
      with_inventory_hostnames:
        - k3s
