all:
  vars:
    ansible_user: vagrant
    system_supporters:
      - "vagrant"
  children:
    k3s:
      vars:
        k3s_cluster_domain: sslip.io
        cluster_fqdn: "{{ ansible_eth1.ipv4.address | replace('.', '-')  }}.{{ k3s_cluster_domain }}"
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        ansible_ssh_user: "vagrant"
        k3s_release_version: v1.17.0+k3s.1
        k3s_write_kubeconfig_mode: 644
      hosts:
        k3snode:
          ansible_ssh_host: 172.17.177.11
          ansible_ssh_private_key_file: /vagrant/local/.vagrant/machines/k3snode/virtualbox/private_key
          k3s_server_manifests_templates:
            - "00-ns-monitoring.yml.j2"
            - "00-ns-operators.yml.j2"
            - "helm-monitoring-operator.yml.j2"
