---
dependency:
  name: galaxy
  options:
    role-file: ./requirements.yml

driver:
  name: vagrant
  provider:
    name: parallels

platforms:
  - name: molecule-instance-1
    box: bento/rockylinux-8.5
    memory: 8192
    cpus: 2
    groups:
      - dockerbased
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../inventory/group_vars/
  playbooks:
    converge: ../../master_playbook-full-install.yml

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy

verifier:
  name: testinfra
  directory: ../../test
  lint:
    name: flake8
